import { ChangeDetectionStrategy, Component } from '@angular/core';
import { javascript } from '@codemirror/lang-javascript';
import { type Extension } from '@codemirror/state';
import { HellCodeEditor } from 'hell-ui/features/code-editor';

@Component({
  selector: 'app-code-editor-read-only-example',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HellCodeEditor],
  template: `
    <hell-code-editor
      [value]="generated"
      [extensions]="extensions"
      ariaLabel="Generated deployment manifest"
      readOnly
    />
  `,
})
export class CodeEditorReadOnlyExample {
  protected readonly extensions: Extension = javascript({ typescript: true });
  protected readonly generated = `// Generated by the deploy pipeline — do not edit.
export const release = {
  version: '2026.7.0',
  channel: 'stable',
  commit: '8495fed',
  builtAt: '2026-07-06T09:14:00Z',
};
`;
}
