server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location ~ \.mjs$ {
    default_type application/javascript;
    try_files $uri =404;
  }

  location ~* \.(?:css|js|json|map|wasm|png|jpg|jpeg|gif|svg|webp|avif|ico|woff2?)$ {
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
